"""
AI Watermark & Audio Provenance Scanner for lyrics-sync.

Detects synthetic music generated by Suno, Udio, and AI audio models via:
1. Metadata & ID3 container markers (Suno/Udio URLs, generator comments, prompt preambles).
2. High-frequency ultrasonic spectral analysis (18–22 kHz band, brickwall roll-offs).
"""

from __future__ import annotations

import re
import time
import logging
from typing import Any, Dict, Optional
import numpy as np

logger = logging.getLogger(__name__)

# Known AI platform identifiers in tags and comments
_SUNO_RE = re.compile(r"\b(?:suno(?:\.com)?|made with suno)\b", re.IGNORECASE)
_UDIO_RE = re.compile(r"\b(?:udio(?:\.com)?|made with udio)\b", re.IGNORECASE)
_GENERIC_AI_RE = re.compile(r"\b(?:musicgen|soundraw|boomy|mubert|elevenlabs|audiocraft)\b", re.IGNORECASE)
_PROMPT_PREAMBLE_RE = re.compile(r"\[(?:Style|Genre|Tags|Prompt|Mood):\s*[^\]]+\]", re.IGNORECASE)


def detect_ai_provenance(
    audio_path: str,
    offset: float = 15.0,
    duration: float = 10.0,
) -> Dict[str, Any]:
    """
    Detect AI provenance and synthetic audio signatures.

    Returns:
      {
        "is_synthetic": bool,
        "confidence": float,
        "detected_source": "suno" | "udio" | "generic_ai" | None,
        "signals": {
          "metadata_marker": bool,
          "prompt_preamble": bool,
          "ultrasonic_anomaly": bool,
          "spectral_cutoff_khz": float,
          "details": list[str]
        },
        "analysis_time_sec": float
      }
    """
    start_time = time.monotonic()
    details = []
    metadata_marker = False
    prompt_preamble = False
    ultrasonic_anomaly = False
    spectral_cutoff_khz = 0.0
    detected_source: Optional[str] = None
    confidence = 0.0

    # ── 1. Metadata Layer (Instant) ──────────────────────────────────────────
    try:
        from mutagen.id3 import ID3
        tags = ID3(audio_path)
        all_text_parts = []
        for frame in tags.values():
            val_str = str(frame)
            if hasattr(frame, "text"):
                val_str += " " + " ".join(str(t) for t in frame.text)
            if hasattr(frame, "url"):
                val_str += " " + str(frame.url)
            all_text_parts.append(val_str)

        full_tag_text = " ".join(all_text_parts)

        if _SUNO_RE.search(full_tag_text):
            metadata_marker = True
            detected_source = "suno"
            confidence = 0.99
            details.append("Detected Suno URL or metadata comment in ID3 tags.")
        elif _UDIO_RE.search(full_tag_text):
            metadata_marker = True
            detected_source = "udio"
            confidence = 0.99
            details.append("Detected Udio URL or metadata comment in ID3 tags.")
        elif _GENERIC_AI_RE.search(full_tag_text):
            metadata_marker = True
            detected_source = "generic_ai"
            confidence = 0.95
            details.append("Detected AI generator string in ID3 tags.")

        if _PROMPT_PREAMBLE_RE.search(full_tag_text):
            prompt_preamble = True
            if not detected_source:
                detected_source = "generic_ai"
                confidence = max(confidence, 0.90)
            details.append("Detected AI generation prompt preamble in lyrics/comments.")

    except Exception as exc:
        logger.debug("ID3 metadata read skipped for %s: %s", audio_path, exc)

    # ── 2. Spectral Signal Layer (Ultrasonic Analysis) ────────────────────────
    try:
        import librosa

        y, sr = librosa.load(audio_path, sr=44100, offset=offset, duration=duration)
        if len(y) == 0:
            y, sr = librosa.load(audio_path, sr=44100, offset=0.0, duration=duration)

        if len(y) > sr:
            # 99% roll-off frequency
            cutoff = float(np.mean(librosa.feature.spectral_rolloff(y=y, sr=sr, roll_percent=0.99)))
            spectral_cutoff_khz = round(cutoff / 1000.0, 1)

            # High-frequency ultrasonic ratio (20kHz - 22.05kHz vs total energy)
            stft = np.abs(librosa.stft(y=y, n_fft=2048, hop_length=512))
            freqs = librosa.fft_frequencies(sr=sr, n_fft=2048)
            idx_20k = np.where(freqs >= 20000)[0][0]
            
            mean_total = float(np.mean(stft)) + 1e-9
            ultrasonic_ratio = float(np.mean(stft[idx_20k:, :]) / mean_total)

            # AI vocoder / synthesis models typically brickwall at 16k-17.5k with an ultrasonic void
            if cutoff < 17500 and ultrasonic_ratio < 0.0005:
                ultrasonic_anomaly = True
                details.append(
                    f"Sharp spectral brickwall cutoff at {spectral_cutoff_khz} kHz with near-zero ultrasonic energy."
                )
                if not detected_source:
                    detected_source = "generic_ai"
                    confidence = max(confidence, 0.65)
            elif cutoff >= 18500 and not metadata_marker and not prompt_preamble:
                # Organic / studio sound with rich high frequency
                confidence = min(confidence, 0.15)

    except Exception as exc:
        logger.warning("Spectral watermark analysis failed for %s: %s", audio_path, exc)

    elapsed = round(time.monotonic() - start_time, 3)

    return {
        "is_synthetic": confidence >= 0.50,
        "confidence": round(confidence, 2),
        "detected_source": detected_source,
        "signals": {
            "metadata_marker": metadata_marker,
            "prompt_preamble": prompt_preamble,
            "ultrasonic_anomaly": ultrasonic_anomaly,
            "spectral_cutoff_khz": spectral_cutoff_khz,
            "details": details,
        },
        "analysis_time_sec": elapsed,
    }
